### ISSUE TITLE
weird C++ crash, probably from nix, only triggerable with nfb (and only via the remote invocation)

### ISSUE THREAD

**Issue by colemickens** [Mic92/nix-fast-build#59]
I did some garbage collection on a machine today, nothing else really out of the normal.

My "builder" box runs a github-runner, and runs a job that uses nfb internally. It seems to still be running.

Sometimes I remote to my "server" box and run nfb (set to remotely copy/build on "builder"). Today, after the GCing on both sides, I've been getting this:

```
▒▒ nfb: .#devShells.x86_64-linux
INFO:nix_fast_build:run nix --experimental-features 'nix-command flakes' flake metadata --json .
warning: Git tree '/home/cole/code/nixcfg' is dirty
INFO:nix_fast_build:run ssh 100.112.194.64 -- 'nix --experimental-features '"'"'nix-command flakes'"'"' shell --extra-experimental-features nix-command --extra-experimental-features flakes '"'"'nixpkgs#nix-eval-
jobs'"'"' -c nix-eval-jobs --gc-roots-dir /tmp/tmp.M5wTxuYP7m --force-recurse --max-memory-size 4096 --workers 2 --flake '"'"'/nix/store/zapw3ii39jpqj45j25alnba9mhr8sf31-source#devShells.x86_64-linux'"'"''
INFO:nix_fast_build:builds: 0, uploads: 0, downloads: 0
warning: unknown setting 'allowed-users'
warning: unknown setting 'trusted-users'
/nix/store/NN152MGPDFCW92B3B03G9KMNLPD9JRIS-gcc-13.2.0/include/c++/13.2.0/optional:477: constexpr _Tp& std::_Optional_base_impl<_Tp, _Dp>::_M_get() [with _Tp = std::__cxx11::basic_string<char>; _Dp = std::_Optio
nal_base<std::__cxx11::basic_string<char>, false, false>]: Assertion 'this->_M_is_engaged()' failed.
/nix/store/NN152MGPDFCW92B3B03G9KMNLPD9JRIS-gcc-13.2.0/include/c++/13.2.0/optional:477: constexpr _Tp& std::_Optional_base_impl<_Tp, _Dp>::_M_get() [with _Tp = std::__cxx11::basic_string<char>; _Dp = std::_Optio
nal_base<std::__cxx11::basic_string<char>, false, false>]: Assertion 'this->_M_is_engaged()' failed.
qerror: while checking worker process, evaluation worker got killed by signal 6 (Aborted)
ERROR:nix_fast_build:nix-eval-jobs exited with 1
INFO:nix_fast_build:run ssh 100.112.194.64 -- rm -rf /tmp/tmp.M5wTxuYP7m
```

If I ssh to that box:
```
╭ raisin  /var/lib/github-actions-runners/raisin-default/work/nixcfg  305ms
╰🡒  nix shell 'nixpkgs#nix-eval-jobs' -c nix-eval-jobs --gc-roots-dir /tmp/tmp.l4yqnHLARO --force-recurse --max-memory-size 4096 --workers 2 --flake
 '/nix/store/qnwbim6jba2dn300ck8iba9qq7z1lpkm-source#devShells.x86_64-linux'
warning: unknown setting 'allowed-users'
warning: unknown setting 'trusted-users'
/nix/store/NN152MGPDFCW92B3B03G9KMNLPD9JRIS-gcc-13.2.0/include/c++/13.2.0/optional:477: constexpr _Tp& std::_Optional_base_impl<_Tp, _Dp>::_M_get()
[with _Tp = std::__cxx11::basic_string<char>; _Dp = std::_Optional_base<std::__cxx11::basic_string<char>, false, false>]: Assertion 'this->_M_is_eng
aged()' failed.
/nix/store/NN152MGPDFCW92B3B03G9KMNLPD9JRIS-gcc-13.2.0/include/c++/13.2.0/optional:477: constexpr _Tp& std::_Optional_base_impl<_Tp, _Dp>::_M_get()
[with _Tp = std::__cxx11::basic_string<char>; _Dp = std::_Optional_base<std::__cxx11::basic_string<char>, false, false>]: Assertion 'this->_M_is_eng
aged()' failed.
error: while checking worker process, evaluation worker got killed by signal 6 (Aborted)
```

but I'm able to manually spot eval some output derivations manually still, and like I said, running the same `nix-fast-build` flake->devshell->direnv from the CI job seems fine.

I realize this is probably a nix bug, but I can only repro though `nix-fast-build` right now. 

Any ideas?

**Comment by colemickens** [comment]
I've tried restarting the nix-daemon on both sides, that didn't really help.

**Comment by colemickens** [comment]
Great, my system registry nixpkgs are on different revs. Really, really, really wish the flake registry didn't exist, or at least that everyone would just not use them for anything.

**Comment by colemickens** [comment]
I guess maybe this is more of a potential nix-eval-jobs bug.

It doesn't happen if I pop a shell from nixos-23.11's `nix-eval-jobs` and run the eval command.

**Comment by anmonteiro** [comment]
I think I'm seeing the same thing, and this was with nix-eval-jobs only ([ci run](https://github.com/nix-ocaml/nix-overlays/actions/runs/8767759284/job/24061381507)), `nix-fast-build` not involved

**Comment by Mic92** [comment]
Fixed in https://github.com/nix-community/nix-eval-jobs/pull/298

**Comment by colemickens** [comment]
Doesn't #52 mean that `nix-fast-build` is still broken, despite the fix submitted to `nix-eval-jobs` (https://github.com/nix-community/nix-eval-jobs/issues/297 + https://github.com/nix-community/nix-eval-jobs/pull/298).

Why not make `nix-fast-build` use `nix-eval-jobs` via the latter's flake?

**Comment by Mic92** [comment]
Could be an option. However I wanted to minimize the copy of nixpkgs that a user has to download.

**Comment by colemickens** [comment]
#52 seems relevant, it was quite disappointing to find out my build tools are relying on global system state, and even more so now that `nix-eval-jobs` is fixed, and I still can't use `nix-fast-build` via its flake.

It feels like a subversion of the point and benefits of flakes, and the resulting downside.

I can send a PR, if you give me an idea what you think the right fix is, or would merge.

**Comment by Mic92** [comment]
A first good step would be to only use nixpkgs#nix-eval-jobs if we have --remote enabled and otherwise rely on things in $PATH instead.

**Comment by colemickens** [comment]
I think that's the case: https://github.com/Mic92/nix-fast-build/blob/f024a66e6a1f83de95aba109287a97dd6ca76127/nix_fast_build/__init__.py#L451-L452

(and then tracing flake->default.nix it looks like the input for `nix-eval-jobs` is an input to derivation, so I assume it uses that, rather than the broader system's PATH for nix-eval-jobs binary.

how would you feel if I:
   * read flake.lock json
   * read out the locked `nix-eval-jobs`
   * (maybe "fragile"), recompose the locked flakeref and use `{nej_locked_flakeref}#nix-eval-jobs` instead of `nixpkgs#nix-eval-jobs`
 ??

**Comment by Mic92** [comment]
For nix-fast-build from the flake we can use the nixpkgs provided, although this would trigger a rebuild everytime there is a nixpkgs bump.
